### ISSUE TITLE
Complex systems

### ISSUE THREAD

**Issue by irhooper** [dpo/MUMPS.jl#3]
I'm trying to solve a sparse matrix system for an electromagnetic field finite element model and would like to use MUMPS via Julia. However, I need to solve complex matrix systems, and so far I can't get it to work. I noticed that in a previous discussion you had with lruthotto (when your code only worked for real matrices) you mentioned that modifying the code to work for complex systems would be relatively trivial, but I'm not having any luck so far. Before I continue to try and solve this issue I wanted to check whether you did modify your code to work for complex systems? It works superbly for real matrices, but I don't want to waste my time trying to figure out the problem if it simply will not work for complex systems at the moment. Many thanks!

**Comment by dpo** [comment]
Implementing complex solves would definitely not be a waste of time. That's number one on the to-do list. I won't be able to get to it this week but I'd be happy to guide you. It would be great if you submitted a pull request!

Basically, the header file `zmumps_c.h` must be `#include`d in [`jmumps.h`](https://github.com/dpo/MUMPS.jl/blob/master/src/jmumps.h), and the relevant parts of [`jmumps.c`](https://github.com/dpo/MUMPS.jl/blob/master/src/jmumps.c) need to be mirrorred for complex data. The easiest might be to change, e.g., [`mumps_initialize()`](https://github.com/dpo/MUMPS.jl/blob/master/src/jmumps.c#L18) to `mumps_initialize_real`, to add a corresponding `mumps_initialize_complex()`, and to decide which one to call in the Julia module. And then to do the same for the other functions. Some common bits of code may be factored out. Nothing difficult but might take a day or so.

**Comment by dpo** [comment]
Double complex arithmetic implemented in https://github.com/dpo/MUMPS.jl/commit/93c43b6b4eb49a4db921744565eee8882b7fada4 (soon to be merged into `master`).

**Comment by irhooper** [comment]
Thanks! I hadn't had a chance to look at doing this myself yet, so you're work is very much appreciated. It works perfectly and my code is now faster by a factor of 5.

**Comment by dpo** [comment]
That's excellent to hear. I really appreciate the feedback!
