### ISSUE TITLE
Error: package coinmumps was not found in the pkg-config search path

### ISSUE THREAD

**Issue by rajhanschinmay** [dpo/MUMPS.jl#4]
Getting error,

Package coinmumps was not found in the pkg-config search path.
Perhaps you should add the directory containing `coinmumps.pc'
to the PKG_CONFIG_PATH environment variable

can anyone help?

**Comment by dpo** [comment]
Sorry I must have missed this somehow. I don't use coinmumps, Did you try adding the path to `coinmumps.pc` to your `PKG_CONFIG_PATH` and exporting this variable before building `MUMPS.jl`?

**Comment by dpo** [comment]
I'm closing as this doesn't seem related to `MUMPS.jl`, but feel free to reopen.
